name: 'Pin with Pinata'
description: 'Pin content to the IPFS using Pinata.'
inputs:
  pinata-api-key:
    description: 'Your Pinata API key.'
    required: true
  pinata-secret-api-key:
    description: 'Your Pinata Secret API key.'
    required: true
  file-to-pin:
    description: 'Path to the file that you want to pin.'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
